"""Construction Compiler CLI — the thin public interface to the Construction Compiler.

Orchestration ONLY: load the Construction Projection → invoke the Construction Compiler → write
artifacts → print diagnostics. It contains **no** lowering / propagation / binding / type / graph /
rendering logic — all of that lives in the compiler passes (`engine/construction_model.py`). Keeping
the CLI logic-free is what makes the eventual move into `pgs_compiler` (as `pgs construction …`) trivial.
The CLI never knows which artifact families exist — the compiler decides.

    python -m pgs_change_mgmt.engine.construction_cli build \
        --projection <cr_ir_dir> --domain blockchain --subdomain chain --out constructed/
    python -m pgs_change_mgmt.engine.construction_cli validate --projection … --domain … --subdomain …
    python -m pgs_change_mgmt.engine.construction_cli graph    --projection … --domain … --subdomain …
    python -m pgs_change_mgmt.engine.construction_cli explain  --projection … --domain … --subdomain …

The Snapshot Admission Gate forms a Compilation Unit (baseline ∪ generated delta ∪ supplementary
artifacts) and asks the Protocol Compiler whether the delta can be admitted into a snapshot:

    python -m pgs_change_mgmt.engine.construction_cli admit \
        --projection <cr_ir_dir> --include <supplementary_dir> --domain blockchain --subdomain chain

Exit codes:  0 = CONSTRUCTION_VALID   ·   2 = CONSTRUCTION_INVALID   ·   1 = usage/error.
"""
from __future__ import annotations

import argparse
import json
import os
from collections import Counter
from pathlib import Path

from . import governance_surface
from .construction_model import build, LOWERING_PIPELINE, PASS_CONSTRAINT, RENDERED_FAMILIES

VALID, INVALID = 0, 2


def _family_of(fqdn: str) -> str:
    return fqdn.split("::")[-1].split("_", 1)[0]


def _classify_supplementary(fqdn: str, domain: str) -> str:
    """Why an artifact had to be *supplied* rather than generated — a classification over the FQDN, not
    the (origin-agnostic) compiler. `UNRENDERED_FAMILY` is the only reason that counts as a construction
    gap: S8 does not render that family yet. The others are legitimate dependencies, not S8's job."""
    if _family_of(fqdn) not in RENDERED_FAMILIES:
        return "UNRENDERED_FAMILY"                                   # a real construction gap
    ns = fqdn.split("::", 1)[0] if "::" in fqdn else domain
    return "EXTERNAL_LIBRARY" if ns != domain else "SHARED_BASELINE"  # legitimate reuse, not a gap


def _admission_report(delta: dict, supplementary: dict, origin: dict, *, domain: str,
                      admission: str | None = None, snapshot: str | None = None,
                      workspace: str | None = None) -> str:
    """The Compilation Unit as a **Protocol Admission Certificate**: it certifies what was *proven*, not
    what the tool did. Three successive gates lead — Construction (did S8 generate everything the CR
    needs?), Admission (does the Protocol Compiler accept the unit?), Snapshot (was a candidate written?)
    — then the evidence. `0 supplementary` is not bookkeeping: it is the machine-verifiable proof that the
    protocol delta is CONSTRUCTION COMPLETE."""
    reasons = {fqdn: _classify_supplementary(fqdn, domain) for fqdn in supplementary}
    gaps = sum(1 for r in reasons.values() if r == "UNRENDERED_FAMILY")   # only unrendered families count
    required = len(delta) + gaps                                          # external/shared are not S8's job
    score = 100.0 if required == 0 else round(len(delta) / required * 100, 1)
    complete = gaps == 0
    # the three gates, grouped — Construction → Admission → Snapshot
    L = ["Compilation Unit", "─" * 52, "",
         f"Construction Status : {'CONSTRUCTION COMPLETE' if complete else 'CONSTRUCTION INCOMPLETE'}"]
    if admission is not None:
        L.append(f"Admission Status    : {admission}")
    if snapshot is not None:
        L.append(f"Snapshot Status     : {snapshot}")
    L += ["", "Artifacts",
          f"  Generated         : {len(delta)}",
          f"  Supplementary     : {len(supplementary)}",
          f"  Completeness      : {len(delta)} / {required} ({score:g}%)"]
    if supplementary:
        L += ["", "Supplementary"]
        for fqdn in sorted(supplementary):
            L.append(f"  {fqdn}")
            if origin.get(fqdn):
                L.append(f"      Origin : {origin[fqdn]}")
            L.append(f"      Reason : {reasons[fqdn]}")
    L += ["", "Result"]
    if complete:
        L += ["  All protocol artifacts required by this CR were generated by S8.",
              "  No construction gap remains."]
    else:
        L += [f"  Construction required {gaps} supplementary artifact(s) S8 does not yet render.",
              "  Close the gap by teaching S8 to render the family, then re-admit."]
    if workspace:
        L += ["", "Workspace"] + [f"  {ln}" for ln in workspace.splitlines()]
    return "\n".join(L)


def _run(args):
    ws = args.workspace or os.environ.get("PGS_WORKSPACE")
    if not ws:
        raise SystemExit("error: set --workspace or PGS_WORKSPACE")
    return build(Path(args.projection), domain=args.domain, subdomain=args.subdomain, workspace=Path(ws))


def _pass_status(res) -> list[tuple[str, str]]:
    by_constraint = Counter(v.constraint for v in res.violations)
    rows = [("Normalize", "PASS")]
    for rule, _fn in LOWERING_PIPELINE:
        con = PASS_CONSTRAINT.get(rule)
        rows.append((rule.replace("DEFAULT_", "").replace("_", " ").title(),
                     "PASS" if not con or by_constraint.get(con, 0) == 0 else "FAIL"))
    return rows


def _report(res, projection: str, artifacts: int) -> int:
    g = res.graph
    print("Construction Compiler\n")
    print(f"  Projection:          {projection}")
    print(f"  Nodes:               {len(g.nodes)}")
    print(f"  Edges:               {len(g.edges)}")
    print("  Passes:")
    for name, status in _pass_status(res):
        print(f"      {name:<26s} {status}")
    if res.violations:
        print("  Violations:")
        for con, n in sorted(Counter(v.constraint for v in res.violations).items()):
            print(f"      {n} {con}")
    else:
        print("  Violations:          NONE")
    ok = not res.violations
    print(f"  Artifacts Generated: {artifacts}")
    print(f"  Compiler Status:     {'CONSTRUCTION_VALID' if ok else 'CONSTRUCTION_INVALID'}")
    return VALID if ok else INVALID


def cmd_build(args) -> int:
    res = _run(args)
    written = 0
    if args.out:
        out = Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        for nid, art in res.artifacts.items():
            if isinstance(art, str):                       # a serialized (constraint-clean) artifact
                (out / f"{nid.split('::')[-1]}.md").write_text(art)
                written += 1
    else:
        written = sum(1 for a in res.artifacts.values() if isinstance(a, str))
    code = _report(res, f"{args.domain}/{args.subdomain}", written)
    if args.out and written:
        print(f"  Output:              {args.out}")
    return code


def cmd_validate(args) -> int:
    res = _run(args)
    return _report(res, f"{args.domain}/{args.subdomain}",
                   sum(1 for a in res.artifacts.values() if isinstance(a, str)))


def cmd_graph(args) -> int:
    g = _run(args).graph
    print("Construction Graph\n")
    print("  Nodes:")
    for concept, n in sorted(Counter(x.concept for x in g.nodes.values()).items()):
        print(f"      {concept:<24s} {n}")
    print("  Edges:")
    for role, n in sorted(Counter(e.role for e in g.edges).items()):
        print(f"      {role:<24s} {n}")
    return VALID


def cmd_admit(args) -> int:
    """Snapshot Admission Gate — form a Compilation Unit and ask the Protocol Compiler whether it
    is admissible into a protocol snapshot (no mutation).

        Compilation Unit  =  Baseline Overlay  ∪  Generated Delta  ∪  Supplementary Artifacts

    The gate is origin-agnostic: the generated delta comes from the Construction Compiler; any
    supplementary artifacts (reused libraries, shared cross-domain artifacts, or temporary support)
    come from `--include` source dirs. The compiler never learns why an artifact is present."""
    from . import compilation_unit as cu
    res = _run(args)
    if res.violations:
        print("Construction is not VALID — nothing to admit (run `validate` / `explain` first).")
        return INVALID
    delta = {nid: a for nid, a in res.artifacts.items() if isinstance(a, str)}       # keep FQDN for ownership
    supplementary = cu.load_sources(args.include, default_namespace=args.domain)     # origin-agnostic sources
    origin = {}                                                                      # fqdn → include-dir (provenance)
    for d in args.include:
        for fqdn in cu.load_sources([d], default_namespace=args.domain):
            origin.setdefault(fqdn, Path(d).name)
    collision = sorted(set(delta) & set(supplementary))
    if collision:
        raise SystemExit(f"error: supplementary artifact(s) collide with the generated delta: {collision}")
    artifacts = {**delta, **supplementary}
    if not artifacts:
        print("Empty Compilation Unit — nothing to admit.")
        return INVALID
    structure = args.structure or f"STRUCTURE_BUILD_{args.domain.upper()}_CONFIG_V0"

    if args.persist:
        # persisted target: write the admitted Compilation Unit to disk as a complete test-snapshot
        # candidate (full isolated build; the Implementation / Execution phases consume this exact
        # snapshot). Heavier than the ephemeral gate — it compiles every structure.
        print(f"Persisting test-snapshot candidate → {args.persist}\n"
              "(isolated full build — compiles every structure; this takes a minute) ...\n")
        p = cu.persist_test_snapshot(artifacts, domain=args.domain, subdomain=args.subdomain,
                                     out_workspace=Path(args.persist))
        if p.ok:
            print(_admission_report(delta, supplementary, origin, domain=args.domain,
                                    admission="PASS", snapshot="ADMITTED_UNVALIDATED",
                                    workspace=f"{p.workspace}\n({len(p.delta_present)} delta artifacts present)"))
            return VALID
        print(_admission_report(delta, supplementary, origin, domain=args.domain, admission="FAIL"))
        print("\nPERSIST FAILED.")
        if p.delta_missing:
            print(f"  delta artifacts missing from snapshot: {p.delta_missing}")
        for ln in p.output.strip().splitlines()[-20:]:
            print("      " + ln)
        return INVALID

    adm = cu.admit(artifacts, domain=args.domain, subdomain=args.subdomain, structure=structure)
    manifest_path = None
    impact_path = None
    impact_doc = None
    if adm.ok and getattr(args, "out", None):
        # Persist the Placement Manifest beside the finale set — the ownership decision, computed once
        # here and consumed verbatim by promotion (never re-resolved downstream).
        manifest_path = cu.write_placement_manifest(adm.unit, Path(args.out))
        # Governance Impact — descriptive discovery of the surface additions this CR requires. Zero
        # authority: governance decides; promotion refuses until the canonical surface satisfies it.
        gi = {"domain": args.domain, "subdomain": args.subdomain,
              "required_changes": governance_surface.impact([f for f in artifacts if governance_surface.is_ct(f)])}
        if gi["required_changes"]["ct_surface"]:
            impact_doc = gi
            impact_path = Path(args.out) / "governance_impact.json"
            impact_path.write_text(json.dumps(gi, indent=2) + "\n")
    print(_admission_report(delta, supplementary, origin, domain=args.domain,
                            admission="PASS" if adm.ok else "FAIL"))
    print()
    print(adm.manifest(structure=structure))
    if manifest_path:
        print(f"\n  Placement manifest : {manifest_path}")
    if impact_path:
        adds = [fq for ch in impact_doc["required_changes"]["ct_surface"] for fq in ch["add"]]
        print(f"  Governance impact  : {impact_path}")
        print(f"    ⚠ governance approval REQUIRED before promotion — {len(adds)} CT surface addition(s):")
        for ch in impact_doc["required_changes"]["ct_surface"]:
            print(f"      {ch['surface']} ({ch['package']}): {', '.join(ch['add'])}")
    if not adm.ok:
        print("\n  --- compiler diagnostics (tail) ---")
        for ln in adm.output.strip().splitlines()[-14:]:
            print("      " + ln)
    return VALID if adm.ok else INVALID


def cmd_explain(args) -> int:
    res = _run(args)
    if not res.violations:
        print("No violations — CONSTRUCTION_VALID.")
        return VALID
    print("Violations (why construction is not yet valid):\n")
    for v in res.violations:
        print(f"  [{v.constraint}] {v.obj}\n      {v.detail}  ({v.gap_class})")
    return INVALID


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="pgs construction", description="Construction Compiler CLI")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name, fn, has_out in [("build", cmd_build, True), ("validate", cmd_validate, False),
                              ("graph", cmd_graph, False), ("explain", cmd_explain, False),
                              ("admit", cmd_admit, False)]:
        p = sub.add_parser(name)
        p.add_argument("--projection", required=True, help="Construction Projection dir (the cr_ir dir)")
        p.add_argument("--domain", required=True)
        p.add_argument("--subdomain", required=True)
        p.add_argument("--workspace", default=os.environ.get("PGS_WORKSPACE"))
        if has_out:
            p.add_argument("--out", help="write serialized artifacts here (constraint-clean nodes only)")
        if name == "admit":
            p.add_argument("--domain-repo", dest="domain_repo",
                           help="path to the domain repo (default: sibling pgs_<domain>)")
            p.add_argument("--structure", help="build STRUCTURE (default: STRUCTURE_BUILD_<DOMAIN>_CONFIG_V0)")
            p.add_argument("--include", action="append", default=[], metavar="DIR",
                           help="supplementary artifact source dir(s) merged into the Compilation Unit "
                                "(origin-agnostic; repeatable)")
            p.add_argument("--persist", metavar="DIR",
                           help="persist the admitted Compilation Unit as a complete test-snapshot "
                                "candidate at DIR (full isolated build; consumed by later phases)")
        p.set_defaults(fn=fn)
    args = ap.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
